name = "Integrals"
uuid = "de52edbc-65ea-441a-8357-d3a637375a31"
version = "4.10.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MonteCarloIntegration = "4886b29c-78c9-11e9-0a6e-41e1f4161f7b"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[weakdeps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HAdaptiveIntegration = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
MCIntegration = "ea1e2de9-7db7-4b42-91ee-0cd1bf6df167"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
IntegralsArblibExt = "Arblib"
IntegralsCubaExt = "Cuba"
IntegralsCubatureExt = "Cubature"
IntegralsDifferentiationInterfaceExt = ["ADTypes", "DifferentiationInterface", "ChainRulesCore"]
IntegralsFastGaussQuadratureExt = "FastGaussQuadrature"
IntegralsForwardDiffExt = "ForwardDiff"
IntegralsHAdaptiveIntegrationExt = "HAdaptiveIntegration"
IntegralsMCIntegrationExt = "MCIntegration"
IntegralsMooncakeExt = ["Mooncake", "Zygote", "ChainRulesCore"]
IntegralsZygoteExt = ["Zygote", "ChainRulesCore"]

[compat]
ADTypes = "1"
Aqua = "0.8"
Arblib = "1"
ArrayInterface = "7"
ChainRulesCore = "1.18"
CommonSolve = "0.2.4"
Cuba = "2.2"
Cubature = "1.5"
DifferentiationInterface = "0.7"
Distributions = "0.25.87"
ExplicitImports = "1.14.0"
FastGaussQuadrature = "0.5,1"
FiniteDiff = "2.12"
ForwardDiff = "0.10.36, 1"
HAdaptiveIntegration = "0.2"
HCubature = "1.7"
LinearAlgebra = "1.10"
MCIntegration = "0.4.2"
MonteCarloIntegration = "0.2"
Mooncake = "0.4.184, 0.5"
Pkg = "1.10"
QuadGK = "2.11"
Random = "1.10"
Reexport = "1.2"
SafeTestsets = "0.1"
SciMLBase = "2.104"
StaticArrays = "1"
Test = "1.10"
Zygote = "0.6.69, 0.7"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HAdaptiveIntegration = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
MCIntegration = "ea1e2de9-7db7-4b42-91ee-0cd1bf6df167"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ADTypes", "Aqua", "Arblib", "StaticArrays", "FiniteDiff", "SafeTestsets", "Test", "Distributions", "ForwardDiff", "Zygote", "ChainRulesCore", "FastGaussQuadrature", "Cuba", "Cubature", "MCIntegration", "Mooncake", "ExplicitImports", "DifferentiationInterface", "Pkg", "HAdaptiveIntegration"]
